# Generated by Django 4.2.3 on 2023-07-26 13:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("to_do_list", "0002_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_done", "-creation_date"]},
        ),
    ]
