# Generated by Django 4.2.3 on 2023-07-26 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("to_do_list", "0003_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"]},
        ),
    ]
